spring:
  application:
    name: springlab2
  datasource:
    password: VZZCFD2CZ60A1T07$
    url: jdbc:postgresql://localhost:5432/postgres
    username: g=khjjxpapru
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 8080